# Generated by Django 4.1 on 2022-09-02 14:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_name', models.CharField(max_length=32, verbose_name='スレッド名')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 9, 2, 23, 23, 7, 527715), verbose_name='作成日時')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='コメント')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 9, 2, 23, 23, 7, 528261), verbose_name='作成日時')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thread_app.thread')),
            ],
        ),
    ]
