# Generated by Django 4.1 on 2022-09-02 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='del_flag',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 23, 37, 35, 444617), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 23, 37, 35, 443715), verbose_name='作成日時'),
        ),
    ]
